// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU98VFqjsemDytuhxsCElVkOzFXboNr5Q',
    appId: '1:1012716261896:web:00d68fd394102d6b09b7bd',
    messagingSenderId: '1012716261896',
    projectId: 'ailanguageapp-f8055',
    authDomain: 'ailanguageapp-f8055.firebaseapp.com',
    storageBucket: 'ailanguageapp-f8055.firebasestorage.app',
    measurementId: 'G-ZBMMG54YR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNro0kQ1on4jHBSYSowlJpBWqH9-DZdhA',
    appId: '1:1012716261896:android:0ae7eaf914326b2309b7bd',
    messagingSenderId: '1012716261896',
    projectId: 'ailanguageapp-f8055',
    storageBucket: 'ailanguageapp-f8055.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARvDl5aXKKnVWfPAvyxlCBrpZ77vw8ekU',
    appId: '1:1012716261896:ios:7dff40bea5e2513f09b7bd',
    messagingSenderId: '1012716261896',
    projectId: 'ailanguageapp-f8055',
    storageBucket: 'ailanguageapp-f8055.firebasestorage.app',
    iosBundleId: 'com.example.aiLanguageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARvDl5aXKKnVWfPAvyxlCBrpZ77vw8ekU',
    appId: '1:1012716261896:ios:7dff40bea5e2513f09b7bd',
    messagingSenderId: '1012716261896',
    projectId: 'ailanguageapp-f8055',
    storageBucket: 'ailanguageapp-f8055.firebasestorage.app',
    iosBundleId: 'com.example.aiLanguageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU98VFqjsemDytuhxsCElVkOzFXboNr5Q',
    appId: '1:1012716261896:web:ac8e21c15107850409b7bd',
    messagingSenderId: '1012716261896',
    projectId: 'ailanguageapp-f8055',
    authDomain: 'ailanguageapp-f8055.firebaseapp.com',
    storageBucket: 'ailanguageapp-f8055.firebasestorage.app',
    measurementId: 'G-YQYGC62F8M',
  );

}